### ISSUE TITLE
Immunity to lightning and explosions

### ISSUE THREAD

**Issue by xiaohanlong** [Azzy380/Attributes#1]
Can you add a stat that lets players turn on or off immunity to lightning or explosions?

**Comment by Azzy380** [comment]
Thats not an attribute, thats a procedure so not really.

**Comment by xiaohanlong** [comment]
> Thats not an attribute, thats a procedure so not really.

So would you make this procedure？

**Comment by Azzy380** [comment]
Nope, this plugin is for attributes

**Comment by xiaohanlong** [comment]
> Nope, this plugin is for attributes

Can you disclose the content of the next update of this plug-in? I like this plugin very much！

and...

Will this proposal be made in your future new plugins?

**Comment by Azzy380** [comment]
Well, attribute modifiers and custom attributes, since they added support for java plugins.

**Comment by xiaohanlong** [comment]
> Well, attribute modifiers and custom attributes, since they added support for java plugins

I don't understand very well. Can the content be more specific? And I want to know when the next update will be. I can't wait.₍ᐢ •͈ ༝ •͈ ᐢ₎♡

**Comment by xiaohanlong** [comment]
I'm from China, do you have any dating apps like Wechat or QQ?Make a friend?(◍•͈⌔•͈◍)

**Comment by Azzy380** [comment]
Custom Attribute means that you can create your own attribute (kinda like mcreators global player variables, but are visible in /attribute command). 
Attribute modifiers are those you add to an item and it modifies an attribute.
