### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Wolfman9623** [Azzy380/Attributes#11]
### Whats the request?

Can you add the Entity dependency to the Calculating Attribute Modifiers global event? I am trying to make custom enchants that give attributes but when I do it shows everything on every item

### Describe the solution you'd like

What I said above

### Additional context (optional)

![image](https://user-images.githubusercontent.com/83597572/231537968-87ee91df-804a-41e6-b10e-524350be1196.png)
![image](https://user-images.githubusercontent.com/83597572/231538524-32206efc-2b4b-47be-be25-1b99dc32b423.png)

**Comment by Wolfman9623** [comment]
Figured out a work around

**Comment by Azzy380** [comment]
Dependencies in global events are set by minecraft and I can't really change them.
