### ISSUE TITLE
[Bug]/[Feature Request]: Adding an attribute modifier to an item removes existing modifiers. 

### ISSUE THREAD

**Issue by Diskman20** [Azzy380/Attributes#17]
### What happened?

I'm working on a mod in which there is an attribute called "crush depth" the depth underwater at which the player starts taking damage. I want to add a crush depth modifier to iron armor in the game, but when I added the modifier, the iron armor's normal armor modifier was removed. I am unsure if this is intended behavior or a bug, or if I've done something wrong. 

### Generator version

Forge 1.20.1

### MCreator version

2023.3

### Example Workspace (optional)

[crushDepthBugMcreatorWorkspace.zip](https://github.com/Azzy380/Attributes/files/12641154/crushDepthBugMcreatorWorkspace.zip)

**Comment by Azzy380** [comment]
unfortunately that's vanilla minecraft behavior. Item attributes are added the same way like you'd do with a command with nbt.

**Comment by Kettle5000** [comment]
> unfortunately that's vanilla minecraft behavior. Item attributes are added the same way like you'd do with a command with nbt.

is there a way to fix this? because i hadnt find any rn
